
on: [push]
name: sn-empshosten1-github
run-name: sn-empshosten1-github

jobs:
  codeql-analysis:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python   # adjust to your language(s)

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          output: results/codeql.sarif
  servicenow-push-test-results:
    runs-on: ubuntu-latest
    name: ServiceNow Test Results
    steps:
    - name: ServiceNow DevOps Unit Test Results
      uses: ServiceNow/servicenow-devops-test-report@v6.0.0
      with:
        # Devops Integration User Name
        devops-integration-user-name: ${{ secrets.SNOW_USER }}
        # Devops Integration User Password
        devops-integration-user-password: ${{ secrets.SNOW_PASSWORD }}
        # ServiceNow Instance Name
        instance-url: ${{ secrets.SNOW_INSTANCE }}
        # Orchestration Tool Id
        tool-id: ${{ secrets.SNOW_TOOL_ID }}
        # Job Name
        job-name: codeql-analysis
        # Github Context
        context-github: ${{ toJSON(github) }}
        # JUnit xml report file name with path
        xml-report-filename: results/codeql.sarif
  deploy-prod:
    name: Deploy to production
    needs: servicenow-push-test-results
    runs-on: ubuntu-latest
    steps:
    - name: ServiceNow DevOps Change Automation
      uses: ServiceNow/servicenow-devops-change@v6.3.0
      with:
        instance-url: ${{ secrets.SNOW_INSTANCE }}
        devops-integration-user-name: ${{ secrets.SNOW_USER }}
        devops-integration-user-password: ${{ secrets.SNOW_PASSWORD }}
        tool-id: ${{ secrets.SNOW_TOOL_ID }}
        job-name: Deploy to production
        context-github: ${{ toJSON(github) }}
        change-request: '{"setCloseCode": true, "attributes": {"u_custom_field": "1", "cmdb_ci": {"name": "AMEA Customer Portal", "sys_class_name": {"name": "Mapped Application Service"}}, "category": "DevOps", "short_description": "Automated Software Deployment using Github!!!", "description": "Automated Software Deployment!!!!"}}'
          
